### ISSUE TITLE
Crash on player join 1.19.3

### ISSUE THREAD

**Issue by Silencx** [The-Fireplace-Minecraft-Mods/Unforgiving-Void#21]
### Mod Version

3.1.5

### What mod loader(s) are you seeing the problem on?

Fabric

### Mod Loader Version

0.14.11

### Problem Description

As my player joins the game the server crashes instantly with a error.

### Steps To Reproduce

Start a fresh install of a fabric server.
Join with a vanilla client.
Crash

### Crash Report or Error Logs

```shell
Description: Exception in server tick loop

java.lang.NoSuchFieldError: field_25095
	at dev.the_fireplace.unforgivingvoid.config.DimensionConfigManager.lambda$new$0(DimensionConfigManager.java:39)
	at dev.the_fireplace.lib.lazyio.hierarchicalconfig.DynamicNamespacedHierarchicalConfigManager.getAllowedModuleIds(DynamicNamespacedHierarchicalConfigManager.java:36)
	at dev.the_fireplace.lib.lazyio.hierarchicalconfig.DynamicNamespacedHierarchicalConfigManager.getUpdatedModuleList(DynamicNamespacedHierarchicalConfigManager.java:49)
	at dev.the_fireplace.lib.lazyio.hierarchicalconfig.DynamicNamespacedHierarchicalConfigManager.get(DynamicNamespacedHierarchicalConfigManager.java:55)
	at dev.the_fireplace.unforgivingvoid.config.DimensionConfigManager.getSettings(DimensionConfigManager.java:59)
	at net.minecraft.class_3222.handler$blm001$tick(class_3222.java:9319)
	at net.minecraft.class_3222.method_14226(class_3222.java:570)
	at net.minecraft.class_3244.method_18784(class_3244.java:266)
	at net.minecraft.class_2535.method_10754(class_2535.java:248)
	at net.minecraft.class_3242.method_14357(class_3242.java:183)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:897)
	at net.minecraft.class_3176.method_3813(class_3176.java:283)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:830)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:676)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:264)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by The-Fireplace** [comment]
1.19.3 is not yet supported.

**Comment by Silencx** [comment]
Any timeline on when it will be supported ?

**Comment by The-Fireplace** [comment]
Not at the moment.

**Comment by Silencx** [comment]
Okay then ill just patiently wait for when it eventually updates!
